### PR TITLE
Make the Maven plugin optional

### PR DESCRIPTION
**Pull request by jonesbusy**
Resolve https://github.com/jfrog/jenkins-artifactory-plugin/issues/748

- [x] This pull request is created in
  the [jfrog/jenkins-artifactory-plugin](https://github.com/jfrog/jenkins-artifactory-plugin) repository.
- [x] All [tests](https://ci.appveyor.com/project/jfrog-ecosystem/jenkins-artifactory-plugin) passed. If this feature is
  not already covered by the tests, I added new tests.
- [x] All [static analysis checks](https://github.com/jfrog/jenkins-artifactory-plugin/actions/workflows/analysis.yml)
  passed.
-----

### CODE REVIEW

**Comment by jonesbusy** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by jonesbusy** [comment]
Hi @yahavi @eyalbe4 Is it something that can be considered ? Over 180 plugins installed on our instance, `artifactory-plugin` is our last one with `maven-plugin` hardcoded dependency.

Thanks!

**Comment by yahavi** [comment]
Hi @jonesbusy, thanks for this contribution!
This PR requires some testing from our side before merging it. We will look into it soon.

**Comment by jonesbusy** [comment]
Hi, any update on this ? 

Thanks @yahavi

**Comment by mgriffin13** [comment]
Has there been any update on this? Cloudbees is really starting to nag because I cannot remove the maven-plugin

**Comment by mgriffin13** [comment]
I installed 3.18.5 and was able to uninstall the maven-plugin. As soon as I did, the entire artifactory plugin started failing, so I had to reinstall the maven-plugin. Seems it can't be made optional without more updates.

**Comment by yahavi** [comment]
Thanks for the feedback, @mgriffin13.
@jonesbusy what do you think? Could you please take a look?

**Comment by mgriffin13** [comment]
I posted a stack trace in this issue https://github.com/jfrog/jenkins-artifactory-plugin/issues/845#issuecomment-1643910825

**Comment by yahavi** [comment]
@jonesbusy @mgriffin13 
Due to the errors it caused, we decided to revert this change.

@jonesbusy 
Please don't hesitate to create a new pull request with a fix that addresses this problem, should you wish to do so.

**Comment by jonesbusy** [comment]
@yahavi I will once https://github.com/jfrog/jenkins-artifactory-plugin/pull/841 is merged and/or this plugin is refreshed it's dependencies

**Pull request merged**
