### PR TITLE
provide a way of retrieving the list of modules including the default one

### PR DESCRIPTION
**Pull request by jdiazdev**
I would like to be able to retrieve the list of modules from the `BuildInfo` object, including the default module. 
Currently the default module is only built when `BuildInfo` is published. My request is to be able to get this information regardless of whether we have published the information or not, so it can be consumed by 3rd parties integrating with Artifactory in the build pipeline.

### CODE REVIEW

**Comment by eyalbe4** [comment]
Thanks for creating this PR @jdiazdev!
It looks like the existing code hasn't been originally designed to save the modules as part of the local build-info instance. before the build-info is published. This basically forced you to add the *getModulesWithDefault()* API. This may be the easiest implementation with the existing code structure, but I'm not sure it is best one.
We're planning to enhance the API, to allow setting a custom module name to the build-info. We'll try doing it in a way that allows getting the list of module from a local build-info instance.

**Comment by jdiazdev** [comment]
thanks for the information @eyalbe4. Do you have any further information you can share about those plans to enhance the API?

**Comment by liron-shalom** [comment]
@jdiazdev - We are working on this feature for our upcoming release, so I want to make sure we are on the same page.
The current situation is the you can iterate over all dependencies or artifacts, aggregated to one list, regardless to which module the file belongs. (buildInfo->getArtifacts/Dependencies)
After the cahnge, we want to enable iterating over the buildInfo's modules in order to go over dependencies or artifscts of each specific module.(buildInfo->getModules->getArtifacts/Dependencies)
In addition we will whitespace the getId() method for a module.
For the "default module" - since we can't store artifcats/dependencies outside of a module, for the generic upload/download, we create a module with a default name (that now can be customize), that contains the uploaded artifacts and the downloaded dependencies. The module is part of the buildInfo object whether it is published or not.

**Comment by eyalbe4** [comment]
@jdiazdev.
Is this something you'd like to further promote and discuss?

**Comment by eyalbe4** [comment]
@jdiazdev, I'm closing this for now, but do let us know if you'd like to further promote this one.

**Pull request closed without merging**
