### PR TITLE
Modernize plugin

### PR DESCRIPTION
**Pull request by rahulsom**
When I started, the master branch did not build.

<details>
  <summary>Error</summary>
  
  ```
❯ mvn verify
[INFO] Scanning for projects...
[WARNING] The POM for org.jenkins-ci.tools:maven-hpi-plugin:jar:3.12 is missing, no dependency information available
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Unresolveable build extension: Plugin org.jenkins-ci.tools:maven-hpi-plugin:3.12 or one of its dependencies could not be resolved: org.jenkins-ci.tools:maven-hpi-plugin:jar:3.12 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced @
[ERROR] Unknown packaging: hpi @ line 29, column 16
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project org.jenkins-ci.plugins:artifactory:3.18.x-SNAPSHOT (/Users/rsomasunderam/src/gh/jfrog/jenkins-artifactory-plugin/pom.xml) has 2 errors
[ERROR]     Unresolveable build extension: Plugin org.jenkins-ci.tools:maven-hpi-plugin:3.12 or one of its dependencies could not be resolved: org.jenkins-ci.tools:maven-hpi-plugin:jar:3.12 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced -> [Help 2]
[ERROR]     Unknown packaging: hpi @ line 29, column 16
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/PluginManagerException
```
</details>

This change gets the build working.

- [x] This pull request is created in the [jfrog/jenkins-artifactory-plugin](https://github.com/jfrog/jenkins-artifactory-plugin) repository.
- [x] All [tests](https://ci.appveyor.com/project/jfrog-ecosystem/jenkins-artifactory-plugin) passed. If this feature is not already covered by the tests, I added new tests.
- [ ] All [static analysis checks](https://github.com/jfrog/jenkins-artifactory-plugin/actions/workflows/analysis.yml)
  passed.
-----

### CODE REVIEW

**Comment by rahulsom** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by rahulsom** [comment]
I scaled back the modernization a tiny bit so I could get the tests passing. We can modernize more as we go along.

**Comment by rahulsom** [comment]
@eyalbe4 @yahavi I've done as little as possible to get the build running and unit tests passing. I think this should help other contributors work with the code base more confidently.

**Comment by rahulsom** [comment]
I'm not sure why this would fail on linux only. Do you have any context?

**Comment by eyalbe4** [comment]
@rahulsom,
There seems to be a dependency collision around the docker tests which are executed on Linux only. 

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.jfrog.hudson.ArtifactoryBuilderTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 16.663 s - in org.jfrog.hudson.ArtifactoryBuilderTest
[INFO] Running org.jfrog.hudson.jfpipelines.JFrogPipelinesHttpClientTest
[INFO] Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: [24](https://github.com/jfrog/jenkins-artifactory-plugin/actions/runs/5704619758/job/15495479028?pr=847#step:15:25).005 s - in org.jfrog.hudson.jfpipelines.JFrogPipelinesHttpClientTest
[INFO] Running org.jfrog.hudson.jfpipelines.JobStatusPayloadTest
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.007 s - in org.jfrog.hudson.jfpipelines.JobStatusPayloadTest
[INFO] Running org.jfrog.hudson.pipeline.ArtifactoryDownloadUploadJsonTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.015 s - in org.jfrog.hudson.pipeline.ArtifactoryDownloadUploadJsonTest
[INFO] Running org.jfrog.hudson.pipeline.UtilsTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.007 s - in org.jfrog.hudson.pipeline.UtilsTest
[INFO] Running org.jfrog.hudson.pipeline.common.types.buildInfo.EnvTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in org.jfrog.hudson.pipeline.common.types.buildInfo.EnvTest
[INFO] Running org.jfrog.hudson.release.ReleaseActionTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in org.jfrog.hudson.release.ReleaseActionTest
[INFO] Running org.jfrog.hudson.release.maven.PomTransformerTest
[INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.05 s - in org.jfrog.hudson.release.maven.PomTransformerTest
[INFO] Running org.jfrog.hudson.trigger.ArtifactoryMultibranchTriggerTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.86 s - in org.jfrog.hudson.trigger.ArtifactoryMultibranchTriggerTest
[INFO] Running org.jfrog.hudson.util.EscapePropertyTest
[INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.006 s - in org.jfrog.hudson.util.EscapePropertyTest
[INFO] Running org.jfrog.hudson.util.converters.ArtifactoryBuilderConverterTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.042 s - in org.jfrog.hudson.util.converters.ArtifactoryBuilderConverterTest
[INFO] Running org.jfrog.hudson.util.converters.CredentialsConfigConverterTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.948 s - in org.jfrog.hudson.util.converters.CredentialsConfigConverterTest
[INFO] Running org.jfrog.hudson.util.converters.DeployerResolverOverriderConverterTest
[INFO] Tests run: 16, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.069 s - in org.jfrog.hudson.util.converters.DeployerResolverOverriderConverterTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 64, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- animal-sniffer-maven-plugin:1.22:check (check) @ artifactory ---
[INFO] Resolved signature org.codehaus.mojo.signature:java18 version as 1.0 from dependencyManagement
[INFO] Checking unresolved references to org.codehaus.mojo.signature:java18:1.0
[INFO] 
[INFO] --- maven-license-plugin:1.8:process (default) @ artifactory ---
[INFO] Generated /home/runner/work/jenkins-artifactory-plugin/jenkins-artifactory-plugin/target/artifactory/WEB-INF/licenses.xml
[INFO] 
[INFO] --- maven-hpi-plugin:3.13:hpi (default-hpi) @ artifactory ---
[INFO] Generating /home/runner/work/jenkins-artifactory-plugin/jenkins-artifactory-plugin/target/artifactory/META-INF/MANIFEST.MF
[INFO] Checking for attached .jar artifact ...
[INFO] Generating jar /home/runner/work/jenkins-artifactory-plugin/jenkins-artifactory-plugin/target/artifactory.jar
[INFO] Building jar: /home/runner/work/jenkins-artifactory-plugin/jenkins-artifactory-plugin/target/artifactory.jar
[INFO] Exploding webapp...
[INFO] Copy webapp webResources to /home/runner/work/jenkins-artifactory-plugin/jenkins-artifactory-plugin/target/artifactory
[INFO] Assembling webapp artifactory in /home/runner/work/jenkins-artifactory-plugin/jenkins-artifactory-plugin/target/artifactory
Warning:  Bundling transitive dependency jackson-annotations-2.14.1.jar (via build-info-api)
Warning:  Bundling transitive dependency jackson-core-2.14.1.jar (via build-info-api)
Warning:  Bundling transitive dependency jackson-databind-2.14.1.jar (via build-info-api)
Warning:  Bundling transitive dependency jackson-dataformat-xml-2.14.1.jar (via build-info-extractor-nuget)
Warning:  Bundling transitive dependency jackson-jaxrs-base-2.10.3.jar (via build-info-extractor-docker)
Warning:  Bundling transitive dependency jackson-jaxrs-json-provider-2.10.3.jar (via build-info-extractor-docker)
Warning:  Bundling transitive dependency woodstox-core-6.4.0.jar (via build-info-extractor-nuget)
Warning:  Bundling transitive dependency docker-java-api-3.2.14.jar (via build-info-extractor-docker)
Warning:  Bundling transitive dependency docker-java-core-3.2.14.jar (via build-info-extractor-docker)
Warning:  Bundling transitive dependency docker-java-transport-jersey-3.2.14.jar (via build-info-extractor-docker)
Warning:  Bundling transitive dependency docker-java-transport-netty-3.2.14.jar (via build-info-extractor-docker)
Warning:  Bundling transitive dependency docker-java-transport-3.2.14.jar (via build-info-extractor-docker)
Warning:  Bundling transitive dependency docker-java-3.2.14.jar (via build-info-extractor-docker)
Warning:  Bundling transitive dependency jsr305-3.0.2.jar (via build-info-extractor-ivy)
[INFO] Bundling direct dependency guava-18.0.jar
Warning:  Bundling transitive dependency jsch.agentproxy.connector-factory-0.0.7.jar (via svnkit)
Warning:  Bundling transitive dependency jsch.agentproxy.core-0.0.7.jar (via svnkit)
Warning:  Bundling transitive dependency jsch.agentproxy.pageant-0.0.7.jar (via svnkit)
Warning:  Bundling transitive dependency jsch.agentproxy.sshagent-0.0.7.jar (via svnkit)
Warning:  Bundling transitive dependency jsch.agentproxy.svnkit-trilead-ssh2-0.0.7.jar (via svnkit)
Warning:  Bundling transitive dependency jsch.agentproxy.usocket-jna-0.0.7.jar (via svnkit)
Warning:  Bundling transitive dependency jsch.agentproxy.usocket-nc-0.0.7.jar (via svnkit)
[INFO] Bundling direct dependency jzlib-1.1.3.jar
Warning:  Bundling transitive dependency junixsocket-common-2.3.2.jar (via build-info-extractor-docker)
Warning:  Bundling transitive dependency junixsocket-native-common-2.3.2.jar (via build-info-extractor-docker)
Warning:  Bundling transitive dependency trilead-ssh2-1.0.0-build222.jar (via svnkit)
[INFO] Bundling direct dependency commons-codec-1.15.jar
[INFO] Bundling direct dependency commons-io-2.8.0.jar
Warning:  Bundling transitive dependency sequence-library-1.0.4.jar (via svnkit)
Warning:  Bundling transitive dependency netty-buffer-4.1.79.Final.jar (via netty-transport)
Warning:  Bundling transitive dependency netty-common-4.1.79.Final.jar (via netty-transport)
Warning:  Bundling transitive dependency netty-handler-4.1.46.Final.jar (via build-info-extractor-docker)
Warning:  Bundling transitive dependency netty-resolver-4.1.79.Final.jar (via netty-transport)
Warning:  Bundling transitive dependency netty-transport-native-epoll-4.1.46.Final.jar (via build-info-extractor-docker)
Warning:  Bundling transitive dependency netty-transport-native-kqueue-4.1.46.Final.jar (via build-info-extractor-docker)
Warning:  Bundling transitive dependency netty-transport-native-unix-common-4.1.46.Final.jar (via build-info-extractor-docker)
[INFO] Bundling direct dependency netty-transport-4.1.79.Final.jar
Warning:  Bundling transitive dependency jakarta.annotation-api-1.3.5.jar (via build-info-extractor-docker)
Warning:  Bundling transitive dependency jakarta.ws.rs-api-2.1.6.jar (via build-info-extractor-docker)
Warning:  Bundling transitive dependency jna-platform-5.6.0.jar (via svnkit)
Warning:  Bundling transitive dependency jna-5.6.0.jar (via svnkit)
Warning:  Bundling transitive dependency platform-3.4.0.jar (via svnkit)
Warning:  Bundling transitive dependency antlr-runtime-3.4.jar (via svnkit)
[INFO] Bundling direct dependency commons-compress-1.21.jar
Warning:  Bundling transitive dependency commons-lang3-3.12.0.jar (via build-info-api)
Warning:  Bundling transitive dependency httpclient-4.5.14.jar (via build-info-api)
Warning:  Bundling transitive dependency httpcore-4.4.16.jar (via build-info-api)
[INFO] Bundling direct dependency ivy-2.5.1.jar
Warning:  Bundling transitive dependency maven-deploy-plugin-3.0.0.jar (via build-info-extractor-maven3)
Warning:  Bundling transitive dependency maven-model-3.8.6.jar (via build-info-extractor-maven3)
Warning:  Bundling transitive dependency bcpkix-jdk15on-1.64.jar (via build-info-extractor-docker)
Warning:  Bundling transitive dependency bcprov-jdk15on-1.64.jar (via build-info-extractor-docker)
[INFO] Bundling direct dependency plexus-classworlds-2.5.2.jar
Warning:  Bundling transitive dependency stax2-api-4.2.1.jar (via build-info-extractor-nuget)
Warning:  Bundling transitive dependency aether-api-1.1.0.jar (via aether-impl)
[INFO] Bundling direct dependency aether-impl-1.1.0.jar
Warning:  Bundling transitive dependency aether-spi-1.1.0.jar (via aether-impl)
Warning:  Bundling transitive dependency aether-util-1.1.0.jar (via aether-impl)
Warning:  Bundling transitive dependency aopalliance-repackaged-2.6.1.jar (via build-info-extractor-docker)
Warning:  Bundling transitive dependency jakarta.inject-2.6.1.jar (via build-info-extractor-docker)
Warning:  Bundling transitive dependency hk2-api-2.6.1.jar (via build-info-extractor-docker)
Warning:  Bundling transitive dependency hk2-locator-2.6.1.jar (via build-info-extractor-docker)
Warning:  Bundling transitive dependency hk2-utils-2.6.1.jar (via build-info-extractor-docker)
Warning:  Bundling transitive dependency osgi-resource-locator-1.0.3.jar (via build-info-extractor-docker)
Warning:  Bundling transitive dependency jersey-apache-connector-2.30.1.jar (via build-info-extractor-docker)
Warning:  Bundling transitive dependency jersey-client-2.30.1.jar (via build-info-extractor-docker)
Warning:  Bundling transitive dependency jersey-common-2.30.1.jar (via build-info-extractor-docker)
Warning:  Bundling transitive dependency jersey-hk2-2.30.1.jar (via build-info-extractor-docker)
Warning:  Bundling transitive dependency javassist-3.[25](https://github.com/jfrog/jenkins-artifactory-plugin/actions/runs/5704619758/job/15495479028?pr=847#step:15:26).0-GA.jar (via build-info-extractor-docker)
Warning:  Bundling transitive dependency jdom2-2.0.6.1.jar (via build-info-extractor-maven3)
[INFO] Bundling direct dependency build-info-api-2.41.3.jar
[INFO] Bundling direct dependency build-info-client-2.41.3.jar
[INFO] Bundling direct dependency build-info-extractor-docker-2.41.3.jar
[INFO] Bundling direct dependency build-info-extractor-go-2.41.3.jar
[INFO] Bundling direct dependency build-info-extractor-gradle-4.33.3.jar
[INFO] Bundling direct dependency build-info-extractor-ivy-2.41.3.jar
[INFO] Bundling direct dependency build-info-extractor-maven3-2.41.3.jar
[INFO] Bundling direct dependency build-info-extractor-npm-2.41.3.jar
[INFO] Bundling direct dependency build-info-extractor-nuget-2.41.3.jar
[INFO] Bundling direct dependency build-info-extractor-pip-2.41.3.jar
[INFO] Bundling direct dependency build-info-extractor-2.41.3.jar
[INFO] Bundling direct dependency build-info-vcs-2.41.3.jar
[INFO] Bundling direct dependency file-specs-java-1.1.1.jar
Warning:  Bundling transitive dependency lz4-java-1.4.1.jar (via svnkit)
[INFO] Bundling direct dependency jcl-over-slf4j-2.0.7.jar
[INFO] Bundling direct dependency slf4j-api-2.0.7.jar
Warning:  Bundling transitive dependency slf4j-simple-1.7.36.jar (via build-info-extractor-npm)
Warning:  Bundling transitive dependency 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.jfrog.hudson.pipeline.integration.DeclarativeITest
Error:  Tests run: 47, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 703.102 s <<< FAILURE! - in org.jfrog.hudson.pipeline.integration.DeclarativeITest
Error:  dockerPullTest(org.jfrog.hudson.pipeline.integration.DeclarativeITest)  Time elapsed: 5.937 s  <<< FAILURE!
java.lang.AssertionError: 
unexpected build status; build log was:
------
Started
Running in Durability level: MAX_SURVIVABILITY
[Pipeline] node
Running on slave0 in /home/runner/work/jenkins-artifactory-plugin/jenkins-artifactory-plugin/target/tmp/jkh8917704811034278836/workspace/test10
[Pipeline] {
[Pipeline] stage
Entering stage rtserverconfig
Proceeding
[Pipeline] rtServer
[Pipeline] stage
Entering stage docker pull stage
Proceeding
[Pipeline] rtDockerPull
Executing command: /bin/sh -c git log --pretty=format:%s -1
[test10] $ java -Djava.io.tmpdir=/home/runner/work/jenkins-artifactory-plugin/jenkins-artifactory-plugin/target/tmp/jkh8917704811034278836/workspace/test10@tmp/artifactory/javatmpdir -cp /home/runner/work/jenkins-artifactory-plugin/jenkins-artifactory-plugin/target/tmp/jkh8917704811034278836/workspace/test10@tmp/artifactory/cache/artifactory-plugin/3.18.x-SNAPSHOT-1690832378087/* org.jfrog.build.extractor.docker.extractor.DockerPull
Jul 31, 2023 7:39:40 PM org.jfrog.build.extractor.packageManager.PackageManagerLogger info
INFO: Pulling image: ***/docker-remote/hello-world:latest using docker daemon host: null
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
SLF4J: Ignoring binding found at [jar:file:/home/runner/work/jenkins-artifactory-plugin/jenkins-artifactory-plugin/target/tmp/jkh8917704811034278836/workspace/test10@tmp/artifactory/cache/artifactory-plugin/3.18.x-SNAPSHOT-1690832378087/slf4j-simple-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.
Error: Exception in thread "main" java.lang.NoClassDefFoundError: io/netty/handler/codec/http/HttpConstants
	at com.github.dockerjava.netty.NettyWebTarget.request(NettyWebTarget.java:104)
	at com.github.dockerjava.netty.NettyWebTarget.request(NettyWebTarget.java:31)
	at com.github.dockerjava.core.exec.PullImageCmdExec.execute0(PullImageCmdExec.java:33)
	at com.github.dockerjava.core.exec.PullImageCmdExec.execute0(PullImageCmdExec.java:13)
	at com.github.dockerjava.core.exec.AbstrAsyncDockerCmdExec.execute(AbstrAsyncDockerCmdExec.java:56)
	at com.github.dockerjava.core.exec.AbstrAsyncDockerCmdExec.exec(AbstrAsyncDockerCmdExec.java:21)
	at com.github.dockerjava.core.exec.AbstrAsyncDockerCmdExec.exec(AbstrAsyncDockerCmdExec.java:12)
	at com.github.dockerjava.core.command.AbstrAsyncDockerCmd.exec(AbstrAsyncDockerCmd.java:21)
	at org.jfrog.build.extractor.docker.DockerJavaWrapper.pullImage(DockerJavaWrapper.java:151)
	at org.jfrog.build.extractor.docker.extractor.DockerPull.execute(DockerPull.java:74)
	at org.jfrog.build.extractor.packageManager.PackageManagerExtractor.executeAndSaveBuildInfo(PackageManagerExtractor.java:33)
	at org.jfrog.build.extractor.docker.extractor.DockerPull.main(DockerPull.java:59)
Caused by: java.lang.ClassNotFoundException: io.netty.handler.codec.http.HttpConstants
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 12 more
ERROR: Couldn't execute docker task. RuntimeException: docker build failed with exit code 1
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
java.lang.RuntimeException: docker build failed with exit code 1
	at org.jfrog.hudson.pipeline.common.Utils.launch(Utils.java:280)
Caused: java.lang.RuntimeException: docker build failed. Couldn't execute docker task. RuntimeException: docker build failed with exit code 1
	at org.jfrog.hudson.pipeline.common.Utils.launch(Utils.java:285)
	at org.jfrog.hudson.pipeline.common.executors.BuildInfoProcessRunner.execute(BuildInfoProcessRunner.java:59)
	at org.jfrog.hudson.pipeline.common.executors.DockerPullExecutor.execute(DockerPullExecutor.java:37)
	at org.jfrog.hudson.pipeline.declarative.steps.docker.DockerPullStep$Execution.runStep(DockerPullStep.java:78)
	at org.jfrog.hudson.pipeline.declarative.steps.docker.DockerPullStep$Execution.runStep(DockerPullStep.java:63)
	at org.jfrog.hudson.pipeline.ArtifactorySynchronousNonBlockingStepExecution.run(ArtifactorySynchronousNonBlockingStepExecution.java:55)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:[26](https://github.com/jfrog/jenkins-artifactory-plugin/actions/runs/5704619758/job/15495479028?pr=847#step:15:27)6)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:11[49](https://github.com/jfrog/jenkins-artifactory-plugin/actions/runs/5704619758/job/15495479028?pr=847#step:15:50))
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:7[50](https://github.com/jfrog/jenkins-artifactory-plugin/actions/runs/5704619758/job/15495479028?pr=847#step:15:51))
Finished: FAILURE
```

**Comment by eyalbe4** [comment]
@rahulsom,
Are you still willing to promote this PR?

**Comment by rahulsom** [comment]
Thanks for the nudge. I'm closing this.

**Pull request closed without merging**
