### PR TITLE
#299 Fix ConfigCredentials converter

### PR DESCRIPTION
**Pull request by Dohbedoh**
Addresses https://github.com/jfrog/jenkins-artifactory-plugin/issues/299

- [x] All [tests](https://ci.appveyor.com/project/jfrog-ecosystem/jenkins-artifactory-plugin) passed. If this feature is not already covered by the tests, I added new tests.
- [x] This pull request is created in the [jfrog/jenkins-artifactory-plugin](https://github.com/jfrog/jenkins-artifactory-plugin) repository.

### CODE REVIEW

**Comment by eyalbe4** [comment]
Thank you for the very detailed analysis in https://github.com/jfrog/jenkins-artifactory-plugin/issues/265 and creating this fix @Dohbedoh!
We'd like to release this one quickly.
Can you please sign our [CLA](https://cla-assistant.io/jfrog/jenkins-artifactory-plugin) so that we can merge this fix?

Also, do you know if ```hudson.util.Scrambler.descramble``` will not descramble, if the string is already descrambled?

**Comment by Dohbedoh** [comment]
> Also, do you know if hudson.util.Scrambler.descramble will not descramble, if the string is already descrambled?

As far as I can tell, the `String` that is read by the converter is the scrambled value (the one in persisted in the `org.jfrog.hudson.ArtifactoryBuilder.xml` by version earlier than 3.6.0). 
I have tested this in test environments several times today. I run out of time to write a unit test for this though and will not be back until Monday :(.

**Comment by eyalbe4** [comment]
@Dohbedoh,
I was trying to look for the code which scrables the password using the ```hudson.util.Scrambler```, but all I can see is that we use ```hudson.util.Secret```, so that passwords are stored encrypted.
Are you sure ```hudson.util.Scrambler``` is needed here, and if so, why?
Thanks

**Comment by Dohbedoh** [comment]
The password was scrambled in 3.5.0 and earlier:

* https://github.com/jfrog/jenkins-artifactory-plugin/blob/artifactory-3.5.0/src/main/java/org/jfrog/hudson/util/Credentials.java#L49-L50

3.6.0 changed this to Secret and introduced the failing converter:

* https://github.com/jfrog/jenkins-artifactory-plugin/commit/cb3dd9051086e2d0c9e50dffeba44044797145bf

So as far as I understand, that converter would only process pre 3.6.0 objects, so password that have a scrambled value. For safety, maybe we could add a condition to check if it is an encrypted value or not ? https://github.com/jenkinsci/jenkins/blob/jenkins-2.235.1/core/src/main/java/hudson/util/Secret.java#L174

**Comment by Dohbedoh** [comment]
A conditional to check if the value is an encrypted value or not is useless as [Secret#fromString](https://github.com/jenkinsci/jenkins/blob/jenkins-2.235.1/core/src/main/java/hudson/util/Secret.java#L241-L254) handled both cases.

**Comment by Dohbedoh** [comment]
@eyalbe4 I have added a new test.

**Comment by eyalbe4** [comment]
@Dohbedoh - thanks so much for this fix!
I actually came across another issue and fixed it here - https://github.com/jfrog/jenkins-artifactory-plugin/pull/303
We'll soon piblish a patch including these two fixes.

**Pull request merged**
