### PR TITLE
bump parent pom to v4, bump jenkins.version to 2.164.3, use plugin bom

### PR DESCRIPTION
**Pull request by jetersen**
fix upper bound dependencies by using both jenkins-bom and plugins-bom we can clean the pom

this solves upper bound dependency conflicts, some are solved by using dependencyManagement such as commons-lang3 it would need a lot of exclusions 🤯

This gets us to a better state, where bundling is our only concern.

```
[WARNING] Bundling transitive dependency backport-util-concurrent-3.1.jar (via build-info-extractor-maven3)
[WARNING] Bundling transitive dependency maven-deploy-plugin-2.8.2.jar (via build-info-extractor-maven3)
[WARNING] Bundling transitive dependency maven-artifact-manager-2.2.1.jar (via build-info-extractor-maven3)
[WARNING] Bundling transitive dependency maven-plugin-registry-2.2.1.jar (via build-info-extractor-maven3)
[WARNING] Bundling transitive dependency maven-profile-2.2.1.jar (via build-info-extractor-maven3)
[WARNING] Bundling transitive dependency maven-project-2.2.1.jar (via build-info-extractor-maven3)
[WARNING] Bundling transitive dependency aether-api-1.1.0.jar (via aether-impl)
[INFO] Bundling direct dependency aether-impl-1.1.0.jar
[WARNING] Bundling transitive dependency aether-spi-1.1.0.jar (via aether-impl)
[WARNING] Bundling transitive dependency aether-util-1.1.0.jar (via aether-impl)
[INFO] Bundling direct dependency build-info-api-2.17.1.jar
[INFO] Bundling direct dependency build-info-client-2.17.1.jar
[INFO] Bundling direct dependency build-info-extractor-go-2.17.1.jar
[INFO] Bundling direct dependency build-info-extractor-gradle-4.15.1.jar
[INFO] Bundling direct dependency build-info-extractor-ivy-2.17.1.jar
[INFO] Bundling direct dependency build-info-extractor-maven3-2.17.1.jar
[INFO] Bundling direct dependency build-info-extractor-npm-2.17.1.jar
[INFO] Bundling direct dependency build-info-extractor-2.17.1.jar
[INFO] Bundling direct dependency build-info-vcs-2.17.1.jar
[WARNING] Bundling transitive dependency aether-api-1.13.1.jar (via build-info-extractor-maven3)
[WARNING] Bundling transitive dependency aether-impl-1.13.1.jar (via build-info-extractor-maven3)
[WARNING] Bundling transitive dependency aether-spi-1.13.1.jar (via build-info-extractor-maven3)
[WARNING] Bundling transitive dependency aether-util-1.13.1.jar (via build-info-extractor-maven3)
[WARNING] Bundling transitive dependency plexus-container-default-1.0-alpha-6.jar (via build-info-extractor-maven3)
[WARNING] Bundling transitive dependency plexus-utils-1.0.2.jar (via build-info-extractor-maven3)
```

- [x] I signed [JFrog's CLA](https://secure.echosign.com/public/hostedForm?formid=5IYKLZ2RXB543N).
- [x] All [tests](https://ci.appveyor.com/project/jfrog-ecosystem/jenkins-artifactory-plugin) passed. If this feature is not already covered by the tests, I added new tests.
- [x] This pull request is created in the [jfrog/jenkins-artifactory-plugin](https://github.com/jfrog/jenkins-artifactory-plugin) repository.
-----

### CODE REVIEW

**Comment by timja** [comment]
@eyalbe4

**Comment by eyalbe4** [comment]
@jetersen,
I get this when trying to build with this PR's branch:

```
[INFO] Adding ignore: module-info
[INFO] Ignoring requireUpperBoundDeps in com.google.code.findbugs:jsr305
[INFO] Ignoring requireUpperBoundDeps in com.google.guava:guava
[WARNING] Rule 4: org.apache.maven.plugins.enforcer.RequireUpperBoundDeps failed with message:
Failed while enforcing RequireUpperBoundDeps. The error(s) are [
Require upper bound dependencies error for org.slf4j:slf4j-api:1.7.25 paths to dependency are:
+-org.jenkins-ci.plugins:artifactory:3.6.x-SNAPSHOT
  +-org.jvnet.hudson.plugins:perforce:1.3.7
    +-org.slf4j:slf4j-api:1.7.25
and
+-org.jenkins-ci.plugins:artifactory:3.6.x-SNAPSHOT
  +-org.jfrog.buildinfo:build-info-extractor-ivy:2.17.x-SNAPSHOT
    +-org.slf4j:slf4j-api:1.7.25 (managed) <-- org.slf4j:slf4j-api:1.5.8
and
+-org.jenkins-ci.plugins:artifactory:3.6.x-SNAPSHOT
  +-org.jfrog.artifactory.client:artifactory-java-client-services:2.6.2
    +-org.slf4j:slf4j-api:1.7.25 (managed) <-- org.slf4j:slf4j-api:1.7.2
and
+-org.jenkins-ci.plugins:artifactory:3.6.x-SNAPSHOT
  +-org.mock-server:mockserver-netty:5.10.0
    +-org.slf4j:slf4j-api:1.7.25 (managed) <-- org.slf4j:slf4j-api:1.7.30
and
+-org.jenkins-ci.plugins:artifactory:3.6.x-SNAPSHOT
  +-org.jenkins-ci.main:maven-plugin:3.6
    +-org.apache.maven:maven-embedder:3.5.4
      +-org.slf4j:slf4j-api:1.7.25 (managed) <-- org.slf4j:slf4j-api:1.4.3
and
+-org.jenkins-ci.plugins:artifactory:3.6.x-SNAPSHOT
  +-org.jenkins-ci.main:maven-plugin:3.6
    +-org.apache.maven.wagon:wagon-ftp:3.3.2
      +-org.slf4j:slf4j-api:1.7.25
and
+-org.jenkins-ci.plugins:artifactory:3.6.x-SNAPSHOT
  +-org.jenkins-ci.main:maven-plugin:3.6
    +-org.apache.maven.wagon:wagon-webdav-jackrabbit:3.3.2
      +-org.slf4j:slf4j-api:1.7.25 (managed) <-- org.slf4j:slf4j-api:1.6.6
and
+-org.jenkins-ci.plugins:artifactory:3.6.x-SNAPSHOT
  +-org.jenkins-ci.plugins:token-macro:2.12
    +-com.jayway.jsonpath:json-path:2.4.0
      +-org.slf4j:slf4j-api:1.7.25 (managed) <-- org.slf4j:slf4j-api:1.6.6
and
+-org.jenkins-ci.plugins:artifactory:3.6.x-SNAPSHOT
  +-org.jvnet.hudson.plugins:perforce:1.3.7
    +-org.slf4j:slf4j-simple:1.4.3
      +-org.slf4j:slf4j-api:1.7.25 (managed) <-- org.slf4j:slf4j-api:1.4.3
and
+-org.jenkins-ci.plugins:artifactory:3.6.x-SNAPSHOT
  +-org.jenkins-ci.plugins:jira:3.0.6
    +-com.atlassian.jira:jira-rest-java-client-core:5.0.4
      +-org.slf4j:slf4j-api:1.7.25 (managed) <-- org.slf4j:slf4j-api:1.7.10
and
+-org.jenkins-ci.plugins:artifactory:3.6.x-SNAPSHOT
  +-org.jenkins-ci.plugins:docker-java-api:3.1.5.2
    +-com.github.docker-java:docker-java:3.1.5
      +-org.slf4j:slf4j-api:1.7.25 (managed) <-- org.slf4j:slf4j-api:1.7.10
and
+-org.jenkins-ci.plugins:artifactory:3.6.x-SNAPSHOT
  +-org.jfrog.artifactory.client:artifactory-java-client-services:2.6.2
    +-org.slf4j:log4j-over-slf4j:1.7.25 (managed) <-- org.slf4j:log4j-over-slf4j:1.7.2
      +-org.slf4j:slf4j-api:1.7.25 (managed) <-- org.slf4j:slf4j-api:1.7.2
and
+-org.jenkins-ci.plugins:artifactory:3.6.x-SNAPSHOT
  +-org.jfrog.artifactory.client:artifactory-java-client-services:2.6.2
    +-ch.qos.logback:logback-classic:1.2.3
      +-org.slf4j:slf4j-api:1.7.25 (managed) <-- org.slf4j:slf4j-api:1.7.2
and
+-org.jenkins-ci.plugins:artifactory:3.6.x-SNAPSHOT
  +-org.mock-server:mockserver-netty:5.10.0
    +-org.mock-server:mockserver-client-java:5.10.0
      +-org.slf4j:slf4j-api:1.7.25 (managed) <-- org.slf4j:slf4j-api:1.7.30
and
+-org.jenkins-ci.plugins:artifactory:3.6.x-SNAPSHOT
  +-org.mock-server:mockserver-netty:5.10.0
    +-org.mock-server:mockserver-core:5.10.0
      +-org.slf4j:slf4j-api:1.7.25 (managed) <-- org.slf4j:slf4j-api:1.7.30
and
+-org.jenkins-ci.plugins:artifactory:3.6.x-SNAPSHOT
  +-org.jenkins-ci.main:jenkins-war:2.164.3
    +-org.slf4j:slf4j-jdk14:1.7.25
      +-org.slf4j:slf4j-api:1.7.25 (managed) <-- org.slf4j:slf4j-api:1.7.30
and
+-org.jenkins-ci.plugins:artifactory:3.6.x-SNAPSHOT
  +-org.jenkins-ci.main:maven-plugin:3.6
    +-org.apache.maven.wagon:wagon-http:3.3.2
      +-org.apache.maven.wagon:wagon-http-shared:3.3.2
        +-org.slf4j:slf4j-api:1.7.25
and
+-org.jenkins-ci.plugins:artifactory:3.6.x-SNAPSHOT
  +-org.jenkins-ci.main:maven-plugin:3.6
    +-org.apache.maven.wagon:wagon-webdav-jackrabbit:3.3.2
      +-org.apache.jackrabbit:jackrabbit-webdav:2.14.4
        +-org.slf4j:slf4j-api:1.7.25 (managed) <-- org.slf4j:slf4j-api:1.6.6
and
+-org.jenkins-ci.plugins:artifactory:3.6.x-SNAPSHOT
  +-org.jenkins-ci.plugins:git:4.1.0
    +-org.jenkins-ci.plugins:git-client:3.2.1 (managed) <-- org.jenkins-ci.plugins:git-client:3.0.0
      +-org.eclipse.jgit:org.eclipse.jgit:5.6.1.202002131546-r
        +-org.slf4j:slf4j-api:1.7.25 (managed) <-- org.slf4j:slf4j-api:1.7.2
and
+-org.jenkins-ci.plugins:artifactory:3.6.x-SNAPSHOT
  +-org.jenkins-ci.plugins:docker-java-api:3.1.5.2
    +-com.github.docker-java:docker-java:3.1.5
      +-org.slf4j:jcl-over-slf4j:1.7.25
        +-org.slf4j:slf4j-api:1.7.25 (managed) <-- org.slf4j:slf4j-api:1.7.10
and
+-org.jenkins-ci.plugins:artifactory:3.6.x-SNAPSHOT
  +-org.mock-server:mockserver-netty:5.10.0
    +-org.mock-server:mockserver-core:5.10.0
      +-org.apache.velocity:velocity-engine-core:2.1
        +-org.slf4j:slf4j-api:1.7.25 (managed) <-- org.slf4j:slf4j-api:1.7.26
and
+-org.jenkins-ci.plugins:artifactory:3.6.x-SNAPSHOT
  +-org.jenkins-ci.main:jenkins-war:2.164.3
    +-org.jenkins-ci.modules:sshd:2.6
      +-org.apache.sshd:sshd-core:1.7.0
        +-org.slf4j:slf4j-api:1.7.25 (managed) <-- org.slf4j:slf4j-api:1.7.30
, 
Require upper bound dependencies error for io.netty:netty-handler-proxy:4.1.31.Final paths to dependency are:
+-org.jenkins-ci.plugins:artifactory:3.6.x-SNAPSHOT
  +-org.jenkins-ci.plugins:docker-java-api:3.1.5.2
    +-com.github.docker-java:docker-java:3.1.5
      +-io.netty:netty-handler-proxy:4.1.31.Final
and
+-org.jenkins-ci.plugins:artifactory:3.6.x-SNAPSHOT
  +-org.mock-server:mockserver-netty:5.10.0
    +-org.mock-server:mockserver-core:5.10.0
      +-io.netty:netty-handler-proxy:4.1.47.Final
, 
Require upper bound dependencies error for javax.servlet:javax.servlet-api:3.1.0 paths to dependency are:
+-org.jenkins-ci.plugins:artifactory:3.6.x-SNAPSHOT
  +-javax.servlet:javax.servlet-api:3.1.0
and
+-org.jenkins-ci.plugins:artifactory:3.6.x-SNAPSHOT
  +-org.mock-server:mockserver-netty:5.10.0
    +-org.mock-server:mockserver-core:5.10.0
      +-javax.servlet:javax.servlet-api:3.1.0 (managed) <-- javax.servlet:javax.servlet-api:4.0.1
and
+-org.jenkins-ci.plugins:artifactory:3.6.x-SNAPSHOT
  +-org.jenkins-ci.main:jenkins-test-harness:2.64
    +-org.eclipse.jetty:jetty-security:9.4.28.v20200408
      +-org.eclipse.jetty:jetty-server:9.4.28.v20200408
        +-javax.servlet:javax.servlet-api:3.1.0 (managed) <-- javax.servlet:javax.servlet-api:4.0.1
and
+-org.jenkins-ci.plugins:artifactory:3.6.x-SNAPSHOT
  +-org.jenkins-ci.main:jenkins-test-harness:2.64
    +-org.eclipse.jetty.websocket:websocket-server:9.4.28.v20200408
      +-org.eclipse.jetty.websocket:websocket-servlet:9.4.28.v20200408
        +-javax.servlet:javax.servlet-api:3.1.0 (managed) <-- javax.servlet:javax.servlet-api:4.0.1
, 
Require upper bound dependencies error for net.sf.jopt-simple:jopt-simple:4.6 paths to dependency are:
+-org.jenkins-ci.plugins:artifactory:3.6.x-SNAPSHOT
  +-org.jenkins-ci.main:jenkins-test-harness:2.64
    +-org.openjdk.jmh:jmh-core:1.23
      +-net.sf.jopt-simple:jopt-simple:4.6
and
+-org.jenkins-ci.plugins:artifactory:3.6.x-SNAPSHOT
  +-org.mock-server:mockserver-netty:5.10.0
    +-org.mock-server:mockserver-core:5.10.0
      +-com.github.java-json-tools:json-schema-validator:2.2.11
        +-net.sf.jopt-simple:jopt-simple:5.0.3
]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:54 min
[INFO] Finished at: 2020-06-23T10:03:50+03:00
[INFO] ------------------------------------------------------------------------
```

**Comment by timja** [comment]
O there's no CI on this, wtf =/

**Comment by jetersen** [comment]
I had mostly solved all these, would be nice to have CI on the PRs... see #286

**Comment by jetersen** [comment]
I'll look into to this in the evening

**Comment by eyalbe4** [comment]
@jetersen,
Would you like to continue working on this?

**Comment by eyalbe4** [comment]
@jetersen, I'm closing this one for now, but please let us know if you'd like to continue promoting this.

**Pull request closed without merging**
