### PR TITLE
Use jersey2-api for jersey jars 

### LINKED ISSUE #735: Plugin should pull in jersey2 libraries via jersey2-api plugin to not conflict with other plugins
**Describe the bug**
Artifactory jenkins plugin packages jersey2 libraries via transitive dependency on build-info-extractor. This causes jersey-hk2 failures if any other jersey-dependant plugin is installed (For example, GitLab Branch Source plugin.)

**To Reproduce**
1. Install Jenkins artifactory plugin
2. Install Gitlab Branch Source plugin
3. Set up multibranch pipeline with gitlab branch source plugin
4. Triggers will fail to update gitlab with jersey-hk2 errors

**Expected behavior**
Jenkins artifactory plugin does not conflict with other plugins.

**Screenshots**
N/A

**Versions**
- Jenkins Artifactory plugin version: 3.18.0
- Jenkins operating system: 2.346.2
- Artifactory Version: N/A as due to it breaking other plugins

**Additional context**

### PR DESCRIPTION
**Pull request by jakegt1**
- [X] This pull request is created in the [jfrog/jenkins-artifactory-plugin](https://github.com/jfrog/jenkins-artifactory-plugin) repository.
- [ ] All [tests](https://ci.appveyor.com/project/jfrog-ecosystem/jenkins-artifactory-plugin) passed. If this feature is not already covered by the tests, I added new tests.
- [ ] All [static analysis checks](https://github.com/jfrog/jenkins-artifactory-plugin/actions/workflows/analysis.yml)
  passed.
-----

Closes #735

### CODE REVIEW

**Comment by jakegt1** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by jakegt1** [comment]
Have ran the unit tests and they are fine. This is a pretty helpful change as otherwise artifactory plugin conflicts with Gitlab plugin.

**Comment by jakegt1** [comment]
Also, this uses a relatively old version of jersey2-api. These will be picked up by runtime, so it doesn't cause much issue in actual systems (will just use whatever jenkins is using.) However, going to a newer version requires massive changes to the pom (need to upgrade the plugin pom from 3.57 -> 4.xx), which is a lot more work then just doing above.

**Comment by jakegt1** [comment]
Not sure what i am supposed to do here, will anyone review this?

**Comment by jakegt1** [comment]
assuming you're using something like plugins.txt.

**Comment by jakegt1** [comment]
Any help here? Not sure how i can solve this problem if the problem is just a missing dependency in the target test jenkins instance.

**Comment by jakegt1** [comment]
Anyone? I am still quite sure this is just because the target jenkins instance does not include jersey2-api.

**Comment by jakegt1** [comment]
@eyalbe4, sorry if this is the wrong person but I would really like this in. It's enough of a pain for me that i currently have to maintain a fork of the plugin.

**Comment by banholzer** [comment]
As we see the very same issue here, can anybody please pick this up?

**Comment by jakegt1** [comment]
I just maintain my own version now because I didn't get a response sadly

**Comment by RobiNino** [comment]
Hi @jakegt1 ,
We apologies for the delay and lack of communication here.
After we fixed our testing suite we're ready to merge this along with a few dependencies that had to be upgraded with jersey in #927 .
Thanks a lot for your contribution!

**Comment by jakegt1** [comment]
@RobiNino is fine, I have worked around it for a while with my own fork anyway, but good for me to not need to maintain it anymore lol. Thanks!

**Pull request merged**
