### PR TITLE
Error in retry upload leads to `currentBuild.result` set t…

### LINKED ISSUE #133: Conan: Error in retry upload leads to `currentBuild.result` set to  `FAILURE`, which always break the job
This ticket is linked to https://github.com/conan-io/conan/issues/4907

I got the problem, that Conan fails, because he got an error '500', when uploading a package.
Unluckily Conan is (at the moment) not retrying the task, as I put him on the commandline arguments.

So I wrote the following groovy script for Jenkins Pipeline:
```groovy
        // Upload to Conan (Artifactory)
        // It happens sometimes, that 2 processes try to change the same value at the same moment. Therefor we repeat the step.
        def max_retry_upload = 5
        for (i = 0; i <max_retry_upload; i++) {
            try {
                client.run command: "upload * --all --force --retry 5 --retry-wait 10 -r ${name} --confirm".toString(), buildInfo: buildInfo
                break
            }
            catch(Exception e) {
                if (i == max_retry_upload - 1) {
                    println "Current Build result: ${currentBuild.result}"
                    println "Error: Unable to upload, sthrow exception..."
                    throw e
                }
                else {
                    println "Current Build result: ${currentBuild.result} (Change status back to SUCCESS)"
                    println "Warning: Unable to upload, sleep & retry..."
                    currentBuild.result = 'SUCCESS'
                    sleep(5 + 5 * Math.random()) // Wait 5 to 10 seconds
                }
            }
        }
```

The script is working, so that Jenkins build the job (also when the first upload fails). But unluckily he still recognize the first error in the upload as error of the complete job. I thought, when I catch the error, he should ignore the failure. The "currentBuild.result" is already set to "FAILURE" instead of "SUCCESS".
Could it be, that the Artifactory plugin first catch the error, then set "currentBuild.result" to "FAILURE" and then rethrow the execption?

### PR DESCRIPTION
**Pull request by yahavi**
…o `FAILURE`, which always break the job

Resolves #133.

### CODE REVIEW

**Comment by climblinne** [comment]
> I'm not sure if we can just change this behavior. A failure in a Conan command should mark the build as a failure, right?

Yes, but I thought, when you have an exception thrown, the build will be anyway marked as failure, if you don't catch it yourself. And this is still happening. 
```groovy
if (failed) { 
   // build.setResult(Result.FAILURE); 
    throw new Run.RunnerAbortedException(); 
} 

```
The problem is, once you set `build.setResult(Result.FAILURE)`  it, you will never be able to unset it.

> 
> If we don't want to automatically fail, maybe we should reconsider if Conan client should return the exit code (the user will choose to fail or not) and how to generate/retrieve the BuildInfo.

I would stay for the exception.

**Comment by jgsogo** [comment]
Oh! Thanks, @climblinne . I didn't realize about the exception being raised and propagated. 👍

**Comment by climblinne** [comment]
There are at total 15 places in code where `setResult` is used. Maybe this should be also changed for others?

**Comment by yahavi** [comment]
@climblinne, I suggest to start with that and see that everything's as expected

**Pull request merged**
