### PR TITLE
add github action ci

### PR DESCRIPTION
**Pull request by jetersen**
Get some sense of whether the build is passing when submitting PRs against this repo.

- [x] I signed [JFrog's CLA](https://secure.echosign.com/public/hostedForm?formid=5IYKLZ2RXB543N).
- [x] All [tests](https://ci.appveyor.com/project/jfrog-ecosystem/jenkins-artifactory-plugin) passed. If this feature is not already covered by the tests, I added new tests.
- [x] This pull request is created in the [jfrog/jenkins-artifactory-plugin](https://github.com/jfrog/jenkins-artifactory-plugin) repository.
-----

### CODE REVIEW

**Comment by jetersen** [comment]
Seems the repo does not have GitHub actions enabled 😢

**Comment by jetersen** [comment]
My action is running here: https://github.com/jetersen/jenkins-artifactory-plugin/actions/runs/130605855
So ya this repo needs to enable GitHub actions inside settings for these to run.

**Comment by eyalbe4** [comment]
@jetersen,
What is the reason for adding a GitHub Action, that will trigger a build for every push? Have you seen https://github.com/jfrog/jenkins-artifactory-plugin/blob/master/appveyor.yml which currently runs the build and tests on Ubuntu and Windows? I guess we can replace AppVeyor with GitHub Actions, but can please share some background about this initiative?

**Comment by jetersen** [comment]
The appveyor's build is not being reported on GitHub so I have no knowledge of you running appveyor.
So perhaps you need to look into fixing the CI so we can get the build status shown on GitHub.
GitHub Actions would show up as a successful or failed check.

**Comment by jetersen** [comment]
One thing is sure you would have faster builds as most of the code below is not needed on GitHub actions as all those dependencies is on both Windows and Linux machines.
https://github.com/jfrog/jenkins-artifactory-plugin/blob/9942f269ca4b6afffdaa1b7876acc7e9e2c00eb8/appveyor.yml#L41-L50

**Comment by eyalbe4** [comment]
Thans for the feedback @jetersen.
BTW, the README actually includes an AppVeyor badge showing the tests status (look at the top of the page).
Also notice that by default, the integration tests are ddisabled. We enable them in appveyor.yml by adding the -DskipITs=false system property. All the details related to the tests are in the README.

**Comment by jetersen** [comment]
So appveyor is setup to only build master branch and not PRs 😢 
So you don't know if something in a PR could potentially break the master branch.

**Comment by eyalbe4** [comment]
@jetersen, 
We do want every PR to run the tests, but we also want the integration tests to run. We haven't yet enabled this on AppVeyor, because we prefer not expose the Artifactory credentials used by the integration tests. We may overcome this, by using a time based access token for each tests cycle, but this requires more work on the tests infra side.

**Comment by jetersen** [comment]
If you use GitHub actions the secrets will only be available. That way you could have external PRs at least built without any secrets just to see for instance maven build passes.

**Comment by eyalbe4** [comment]
@jetersen,
Secrets are good, but they don't solve the issue completely. Since this is a security concern, let me know if you'd like us to discuss this on a private channel. Feel free to send me an email and I'll share with you our security concerns around this approach. As I wrote above, there are secure solutions for this, we just need to implement them.

**Comment by jetersen** [comment]
We could ignore running integrations on PRs and just have it on master, at least this improves the current situation.

**Comment by eyalbe4** [comment]
@jetersen,
If we see that we can't put in place the functionality that allows running integration tests in a few weeks time, we'll go with you r approach. The integration tests coverage though dramatically exceeds the unit tests, so we really want to be able to run them on new PRs.

**Pull request closed without merging**
