### PR TITLE
Deprecation updates

### PR DESCRIPTION
**Pull request by michaelcusick**
- [ ] All [tests](https://ci.appveyor.com/project/jfrog-ecosystem/jenkins-artifactory-plugin) passed. If this feature is not already covered by the tests, I added new tests.
- [ ] This pull request is created in the [jfrog/jenkins-artifactory-plugin](https://github.com/jfrog/jenkins-artifactory-plugin) repository.
-----

### CODE REVIEW

**Comment by bromps** [comment]
I have read the CLA Document and I hereby sign the CLA

recheckcla

**Comment by bromps** [comment]
**recheckcla**

**Comment by bromps** [comment]
**recheckcla**
___
***I have read the CLA Document and I hereby sign the CLA***
___

**Comment by bromps** [comment]
recheckcla

**Comment by yahavi** [comment]
Thanks for your contribution, @michaelcusick!
Before merging your PR, our CLA bot have to add you to the contributors list. 
Currently, our CLA bot does not handle properly any spaces or lines between the below sentence. We are working to improve it in the near future.

Please just copy and paste the following sentence as is:

I have read the CLA Document and I hereby sign the CLA

**Comment by michaelcusick** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by yahavi** [comment]
recheckcla

**Pull request merged**
