### PR TITLE
Update plugin parent POM; use plugin BOM

### PR DESCRIPTION
**Pull request by basil**
Updates the build of this plugin to conform to Jenkins best practices:

- Use the latest [plugin parent POM](https://github.com/jenkinsci/plugin-pom)
- Use the [plugin BOM](https://github.com/jenkinsci/bom) corresponding to the Jenkins baseline (2.235.x)

The references to SLF4J can be removed from this plugin, as Jenkins core has bundled SLF4J since at least 2.235.x.

- [x] This pull request is created in
  the [jfrog/jenkins-artifactory-plugin](https://github.com/jfrog/jenkins-artifactory-plugin) repository.
- [x] All [tests](https://ci.appveyor.com/project/jfrog-ecosystem/jenkins-artifactory-plugin) passed. If this feature is
  not already covered by the tests, I added new tests.
- [x] All [static analysis checks](https://github.com/jfrog/jenkins-artifactory-plugin/actions/workflows/analysis.yml)
  passed.

### CODE REVIEW

**Comment by yahavi** [comment]
@basil thanks for this contribution!
I'm getting the following error when trying to run the integration tests:

```
2022-03-25 14:57:20.160+0000 [id=63]    SEVERE  jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Jenkins Git plugin v4.6.0 (git)
java.io.IOException: Failed to load: Jenkins Git plugin (4.6.0)
 - Update required: Jenkins Parameterized Trigger plugin (2.21) to be updated to 2.39 or higher
        at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:934)
        at hudson.PluginManager$2$1$1.run(PluginManager.java:548)
        at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
        at jenkins.model.Jenkins$5.runTask(Jenkins.java:1131)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
        at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

Errors in dependent plugins prevent the plugin from be loaded to the plugin manager in the integration tests.
This can be reproduced easily by running `mvn hpi:run`

**Comment by basil** [comment]
@yahavi As of commit 870eaa18 `mvn clean verify -Dtest=InjectedTest` passes.

**Comment by yahavi** [comment]
@basil, to run the integration tests, please follow the instructions here: https://github.com/jfrog/jenkins-artifactory-plugin#integration-tests
You'll need a JFrog instance, but you get one for free here: https://jfrog.com/start-free. With that instance, you can run most of the tests (except Distribution tests).

**Comment by basil** [comment]
> @basil, to run the integration tests

You are assuming that I have the time and interest in running the integration tests to begin with. I do not. Please do the testing yourself and report the results.

**Comment by eyalbe4** [comment]
@basil,
I think that @yahavi's request is reasonable from a contributor to this repository. If you need assistance or have questions about running the tests, I'm sure the maintainers of this repository would be more than willing to assist.

**Pull request closed without merging**
