### PR TITLE
Fix ConcurrentModificationException in UnifiedPromoteBuildAction

### PR DESCRIPTION
**Pull request by yahavi**
- [x] This pull request is created in
  the [jfrog/jenkins-artifactory-plugin](https://github.com/jfrog/jenkins-artifactory-plugin) repository.
- [x] All [tests](https://ci.appveyor.com/project/jfrog-ecosystem/jenkins-artifactory-plugin) passed. If this feature is
  not already covered by the tests, I added new tests.
- [x] All [static analysis checks](https://github.com/jfrog/jenkins-artifactory-plugin/actions/workflows/analysis.yml)
  passed.
-----

Fix the following issue:
```
Caused: java.lang.RuntimeException: Failed to serialize org.jfrog.hudson.release.promotion.UnifiedPromoteBuildAction#promotionCandidates for class org.jfrog.hudson.release.promotion.UnifiedPromoteBuildAction
```

https://www.jfrog.com/jira/browse/HAP-1487?focusedCommentId=218664&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-218664

### CODE REVIEW

**Review by eyalbe4 — APPROVED** [review]

**Comment by mwolniewicz** [comment]
Hi, @eyalbe4 @yahavi when new artifactory plugin containing the fix is going to be released?

**Comment by yahavi** [comment]
Hi @mwolniewicz,
Jenkins Artifactory plugin 3.17.4 is released and will be available shortly in the plugin manager.
This version includes a fix for this issue.
We'd appreciate your feedback on that!

**Comment by mwolniewicz** [comment]
Hello,
Thanks! We will test the change and let you know if issue is fixed.

**Comment by mwolniewicz** [comment]
Hi,

@yahavi sorry for my late reply. I can confirm that the issue is fixed in version 3.17.4

**Pull request merged**
